### ISSUE TITLE
any more examples

### ISSUE THREAD

**Issue by harrisoftware** [lazychaser/illuminate-menu#1]
Hi
I want to use this package. Do you have any examples of how to practically use this - like how to turn a returned collection into a menu for example? 

$menuitems = array();
$Themes = Themes::all();
foreach ($Themes as $theme) {
    $menuitems[]=    [ 'label' => $theme->label, 'url' => $theme->url ];
}

Menu::render($menuitems);

Is this anywhere close?

or is it as simple as

Menu::render($Themes); 

if there are label and url fields in the returned collection.

**Comment by lazychaser** [comment]
This will work:

``` php
$Themes->map(function ($item) { return [ 'label' => $item->label, 'url' => $item->url ]; });
```

**Comment by harrisoftware** [comment]
Awesome, thanks.

FYI I had to add ->toArray() as the statement above returns a Collection

**Comment by lazychaser** [comment]
Better to use `all()` =)

**Comment by harrisoftware** [comment]
this is working

```
 $menuitems = $Items->map(function ($item) use ($urlroot) { return [ 'label' => $item->name, 'url' => $urlroot.'/'.$item->id, 'secure' => true ]; })->toArray(); 
```

**Comment by lazychaser** [comment]
Just switch `toArray` to `all`

**Comment by harrisoftware** [comment]
great! that works too. Not sure why tho. all() returns an array? not a collection? I've always had trouble with which returns what...

**Comment by lazychaser** [comment]
`all()` just returns underlying items, if this is a collection of models, it would return an array of eloquent models, since we converted models to arrays already, we don't need to use `toArray` that will do extra work.
