### ISSUE TITLE
url redirect from menu seems hardcoded to http only

### ISSUE THREAD

**Issue by harrisoftware** [lazychaser/illuminate-menu#2]
```
        foreach ($Items as $item) {
            $menuitems[] = [ 'label' => $item->name, 'url' => $url.'/'.$item->id ];
        }
```

the route served over https://server.local/
when these menu items are rendered, the URL reverts to http://server.local/$url

is that hardcoded??

**Comment by lazychaser** [comment]
There is a `secure` option, set it to `true`.

**Comment by harrisoftware** [comment]
Perfect, thanks

**Comment by lazychaser** [comment]
You can also provide generated url, if `url` options contains scheme, it is left as is.
