### ISSUE TITLE
using target=_blank

### ISSUE THREAD

**Issue by harrisoftware** [lazychaser/illuminate-menu#3]
this is working well for me, but I'd like to be able to specify opening the url in a new window (via target=_blank) or some other switch like you have for 'secure'.
Is this already available and I just don't know how to do it?
thanks in advance

**Comment by lazychaser** [comment]
Something such `linkOptions` would solve this. I'll add it later.

**Comment by harrisoftware** [comment]
thanks! We'd all really appreciate it! :)

**Comment by harrisoftware** [comment]
any idea when tho?

**Comment by lazychaser** [comment]
Done
