### ISSUE TITLE
ability to ajax

### ISSUE THREAD

**Issue by harrisoftware** [lazychaser/illuminate-menu#4]
also, what about the ability to ajax; if one uses an ajax syntax as url
using

`$menuitems = $Items->map(function ($item) use ($urlroot) { return [ 'label' => $item->name, 'url' => "javascript: $.get('".$urlroot."/".$item->id."', function(data){ $('#form-placeholder').html(data);});", 'secure' => true ]; })->all();`

you end up with 
   `<a href="https://project.local/javascript: $.get('reports/8', function(data){ $('#form-placeholder').html(data);});">Product:Criteria matrix</a>`

instead of
    `<a href="javascript: $.get('https://project.local/reports/8', function(data){ $('#form-placeholder').html(data);});">Product:Criteria matrix</a>`

should I be using some other method/syntax?

**Comment by lazychaser** [comment]
After I add `linkOptions` in a couple minutes, you'll be able to specify `onclick` action

**Comment by harrisoftware** [comment]
I really love the simplicity of this package.
I was wondering if you could provide a few more  real-world examples of how to use it to help out laravel newbies. I think people would really use it!

Anyway,  with this new version, I tried 

```
<?php $menuitems = $Items->map(function ($item) use ($urlroot, $linkoptions) { return [ 'label' => $item->name, 'url' => $urlroot.'/'.$item->id, 'secure' => false, 'linkOptions' => $linkoptions ]; })->all(); ?>
<div class="menuitem" style="margin-top:-3px;">
<div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="width:90px;">
        {{ $btnText }} <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">

      {!! Menu::items($menuitems) !!}

    </ul>
</div>
```

</div>

$menutiems is built inside a partial.view. The $linkoptions comes in to the partial.view that I include to build these kinds of menu buttons. This was working great (before the addition of linkOptions). Here's the include from the maln view:

```
// reports button menu
@include('partials.BuildMenuFromModel',array('btnText'=>'Reports', 'Items'=>Report::orderBy('id', 'asc')->get(), 'urlroot'=>'reports', 'linkoptions' => array('target'=>'_blank') ))
```

But now I get an error:
htmlentities() expects parameter 1 to be string, array given
MenuBuilder.php:264

$menuitems look good, from what I can tell

```
array:8 [▼
  0 => array:4 [▼
"label" => "References"
"url" => "reports/1"
"secure" => false
"linkOptions" => array:1 [▼
  "target" => "_blank"
    ]
]
  1 => array:4 [▶]
  2 => array:4 [▶]
  3 => array:4 [▶]
  4 => array:4 [▶]
  5 => array:4 [▶]
  6 => array:4 [▶]
  7 => array:4 [▶]
]
```

looks like it errors when its trying to deal with $attributes (MenuBuilder:264)

any ideas? what am I doing wrong here?

**Comment by harrisoftware** [comment]
UPDATE:
I looked back in my terminal log:

```
- Removing kalnoy/illuminate-menu (v1.1.1)
- Installing kalnoy/illuminate-menu (v1.1.2)
Loading from cache
```

looks like the latest (1.2.0) wasn't installed via composer?
So I manually copied the new version into my vendor/kalnoy folder and the above all works!
AWESOME!

can you push this version to wherever it needs to go so that composer will update to it? thanks.

**Comment by harrisoftware** [comment]
Can you shed some light on how I might get this result:

```
<a href="javascript:void();" target="_blank" onclick="doIt();">menu item</a>
```

instead of:

```
<a href="http://localhost/javascript:void();" target="_blank" onclick="doIt();">menu item</a>
```

and how does one turn off the full path URI anyway?

**Comment by lazychaser** [comment]
Something's wrong with the packagist\github, I can't update the package, It doesn't see the latest tag. Here is what you need:

``` php
{!! Menu::item([ 'url' => '#', 'linkOptions' => [ 'onclick' => 'doIt();', 'target' => '_blank' ], 'label' => 'menu item' ]) !!}
```

**Comment by harrisoftware** [comment]
that works great. any idea on when the packagist\github will be corrected?

**Comment by lazychaser** [comment]
v1.2.0 is available now!

**Comment by harrisoftware** [comment]
awesome, thanks. I know its probably your least favorite thing to do, but some real world examples to illustrate some of the functionality of this fairly powerful, yet small package would be much appreciated and may help it get some real traction in the laravel 5 community.

**Comment by lazychaser** [comment]
Ok, thanks, will do! Any considerations?

**Comment by lazychaser** [comment]
I'm going to implement following in v2:
-  Abandon link options and instead apply attributes from options array to `a` rather than to `li`
-  Add `MenuItem` interface to support passing objects for rendering menu items (rather than mapping a collection)
-  Support of bootstrap v4 (painfull)

**Comment by harrisoftware** [comment]
I haven't experimented with this but I'm assuming setting an attribute of 'onclick'=>'doIt();' with a 'url'=>'#' results in what i think I needed, no? 
or does the `<a href="#">` override the `<li onclick='doIt();'>`, or does the `<li onclick` not even work that way?

(Initially, I just wanted it to target a new window, so the linkOptions was the best solution for that tho!)

Ideally, the standard seems to be something like

```
<li>   <a href='javascript:void(0);'><span onclick='doIt();'>click me</span></a>  </li>
```

but I guess there's many ways of doing it. 

what are your thoughts on this? It does seem like the combination of the attributes and the linkOptions is the most flexible if there was some way of 'switching off' the `<a>` tag when using an onclick attribute so that they don't conflict.

**Comment by lazychaser** [comment]
Actually, I've already created `v2.0.0@dev` branch where you can specify `href` property which will be set as is on the `<a>` tag. But the layout of the package was rewritten to reflect changes in Bootstrap 4. 

Anyways, it's a common practice which I use: `<a href="#" onclick="doIt();return false;">My link</a>`
